name: Build and Test

on: [push]

jobs:
  core:
    runs-on: ubuntu-latest
    env:
      sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test

  example:
    runs-on: ubuntu-latest
    env:
      sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew :example:build
      - name: Test
        run: ./gradlew :example:test